from pathlib import Path
p=Path('src/visual-game.js')
s=p.read_text()
if 'function drawOfficePropsArt(' in s:
    raise SystemExit(0)

# Hide prototype body rendering; custom canvas art will draw the bodies.
s=s.replace("function woodRender(kind){return kind==='beam'?{fillStyle:'#c9823c',strokeStyle:'#6f3b18',lineWidth:3}:{fillStyle:'#a95d2b',strokeStyle:'#5a2f16',lineWidth:3}}","function woodRender(kind){return{visible:false}}")
s=s.replace("render:{fillStyle:'rgba(157,225,245,.36)',strokeStyle:'rgba(224,250,255,.95)',lineWidth:3}","render:{visible:false}")
s=s.replace("render:{fillStyle:'#6f7f8d',strokeStyle:'#303c46',lineWidth:4}","render:{visible:false}")
s=s.replace("render:{fillStyle:'#8b9196',strokeStyle:'#4d545a',lineWidth:4}","render:{visible:false}")
s=s.replace("render:{fillStyle:'#596878',strokeStyle:'#26323d',lineWidth:4}","render:{visible:false}")
s=s.replace("render:{fillStyle:'#263643',strokeStyle:'#8fd5e8',lineWidth:4}","render:{visible:false}")
s=s.replace("render:{fillStyle:'#e1e4e5',strokeStyle:'#59636a',lineWidth:4}","render:{visible:false}")

start=s.index('function drawBackground(ctx)')
end=s.index('function drawSlingshot(ctx)',start)
new_bg="""function drawBackground(ctx){const w=render.canvas.width,h=render.canvas.height,pr=render.options.pixelRatio||1;ctx.save();ctx.setTransform(1,0,0,1,0,0);const floor=(floorY-4)*pr;const wall=ctx.createLinearGradient(0,0,0,floor);wall.addColorStop(0,'#dfe9f5');wall.addColorStop(.58,'#f7fbff');wall.addColorStop(1,'#e9dfd0');ctx.fillStyle=wall;ctx.fillRect(0,0,w,floor);ctx.fillStyle='#cad3df';ctx.fillRect(0,0,w,74*pr);ctx.strokeStyle='rgba(80,98,120,.18)';ctx.lineWidth=2*pr;for(let x=0;x<w;x+=160*pr){ctx.beginPath();ctx.moveTo(x,0);ctx.lineTo(x,74*pr);ctx.stroke()}ctx.fillStyle='#fff2cf';ctx.shadowColor='rgba(255,220,150,.5)';ctx.shadowBlur=28*pr;ctx.fillRect(w*.77,17*pr,170*pr,34*pr);ctx.shadowBlur=0;const wx=w*.29,wy=115*pr,ww=w*.62,wh=Math.max(250*pr,floor-wy-85*pr);ctx.fillStyle='#a9d9f4';ctx.fillRect(wx,wy,ww,wh);const sky=ctx.createLinearGradient(0,wy,0,wy+wh);sky.addColorStop(0,'#79c8f3');sky.addColorStop(1,'#dff3ff');ctx.fillStyle=sky;ctx.fillRect(wx,wy,ww,wh);ctx.globalAlpha=.42;for(let i=0;i<13;i++){const bw=(34+(i%4)*14)*pr,bh=(95+(i%5)*43)*pr,x=wx+i*(ww/12)-10*pr,y=wy+wh-bh;ctx.fillStyle=i%2?'#75a9c3':'#8ab7cb';ctx.fillRect(x,y,bw,bh);ctx.fillStyle='rgba(244,248,220,.5)';for(let yy=y+14*pr;yy<y+bh-8*pr;yy+=23*pr)for(let xx=x+8*pr;xx<x+bw-6*pr;xx+=15*pr)ctx.fillRect(xx,yy,5*pr,8*pr)}ctx.globalAlpha=1;ctx.strokeStyle='#7f94a8';ctx.lineWidth=8*pr;ctx.strokeRect(wx,wy,ww,wh);for(let i=1;i<4;i++){ctx.beginPath();ctx.moveTo(wx+ww*i/4,wy);ctx.lineTo(wx+ww*i/4,wy+wh);ctx.stroke()}ctx.fillStyle='#e8dfd2';ctx.fillRect(0,floor-76*pr,w,76*pr);ctx.fillStyle='#9b6b42';ctx.fillRect(0,floor,w,h-floor);ctx.fillStyle='#704627';ctx.fillRect(0,floor,w,13*pr);ctx.strokeStyle='rgba(77,44,23,.26)';ctx.lineWidth=2*pr;for(let x=0;x<w;x+=130*pr){ctx.beginPath();ctx.moveTo(x,floor);ctx.lineTo(x+18*pr,h);ctx.stroke()}ctx.fillStyle='rgba(255,255,255,.22)';ctx.fillRect(0,floor-7*pr,w,7*pr);ctx.restore()}\n"""
s=s[:start]+new_bg+s[end:]

# Replace slingshot rendering.
start=s.index('function drawSlingshot(ctx)')
end=s.index('function drawHeroQueue(ctx)',start)
new_sling="""function drawSlingshot(ctx){ctx.save();ctx.lineCap='round';ctx.lineJoin='round';ctx.shadowColor='rgba(35,18,8,.35)';ctx.shadowBlur=18;ctx.shadowOffsetY=10;const grad=ctx.createLinearGradient(anchor.x-55,anchor.y,anchor.x+55,floorY);grad.addColorStop(0,'#7b3c18');grad.addColorStop(.45,'#c57932');grad.addColorStop(1,'#6e3518');ctx.strokeStyle=grad;ctx.lineWidth=30;ctx.beginPath();ctx.moveTo(anchor.x,floorY-7);ctx.lineTo(anchor.x,anchor.y+18);ctx.moveTo(anchor.x,anchor.y+25);ctx.lineTo(anchor.x-53,anchor.y-50);ctx.moveTo(anchor.x,anchor.y+25);ctx.lineTo(anchor.x+53,anchor.y-50);ctx.stroke();ctx.shadowBlur=0;ctx.strokeStyle='#e8a050';ctx.lineWidth=6;ctx.beginPath();ctx.moveTo(anchor.x-6,floorY-16);ctx.lineTo(anchor.x-6,anchor.y+14);ctx.stroke();ctx.fillStyle='#8b4c24';ctx.strokeStyle='#3d2113';ctx.lineWidth=4;ctx.beginPath();ctx.roundRect(anchor.x-72,floorY-4,144,28,8);ctx.fill();ctx.stroke();ctx.fillStyle='#4b5660';for(const x of [anchor.x-42,anchor.x+42]){ctx.beginPath();ctx.arc(x,floorY+10,6,0,Math.PI*2);ctx.fill()}if(!detached&&ball){ctx.strokeStyle='#332016';ctx.lineWidth=8;ctx.beginPath();ctx.moveTo(anchor.x-53,anchor.y-50);ctx.lineTo(ball.position.x,ball.position.y);ctx.lineTo(anchor.x+53,anchor.y-50);ctx.stroke()}ctx.restore()}\n"""
s=s[:start]+new_sling+s[end:]

# Add custom material and prop art before drawHero.
marker='function drawHero(ctx)'
idx=s.index(marker)
art="""function roundedBodyPath(ctx,b,w,h,r=7){ctx.translate(b.position.x,b.position.y);ctx.rotate(b.angle);ctx.beginPath();ctx.roundRect(-w/2,-h/2,w,h,r)}
function drawWorldArt(ctx){for(const b of Composite.allBodies(engine.world)){if(b.gameType==='structure'){ctx.save();roundedBodyPath(ctx,b,b.woodWidth,b.woodHeight,7);const g=ctx.createLinearGradient(-b.woodWidth/2,0,b.woodWidth/2,0);g.addColorStop(0,b.weakPoint?'#dba04b':'#9a4f20');g.addColorStop(.42,b.weakPoint?'#f4bd65':'#d88a3d');g.addColorStop(1,b.weakPoint?'#b76b22':'#804018');ctx.fillStyle=g;ctx.shadowColor='rgba(45,22,8,.32)';ctx.shadowBlur=8;ctx.shadowOffsetY=5;ctx.fill();ctx.shadowBlur=0;ctx.strokeStyle='#5a2c14';ctx.lineWidth=3;ctx.stroke();ctx.strokeStyle='rgba(255,214,143,.45)';ctx.lineWidth=2;ctx.beginPath();ctx.moveTo(-b.woodWidth*.35,-b.woodHeight*.18);ctx.lineTo(b.woodWidth*.3,-b.woodHeight*.18);ctx.stroke();ctx.fillStyle='#4d5660';for(const x of [-b.woodWidth*.39,b.woodWidth*.39]){ctx.beginPath();ctx.arc(x,0,4,0,Math.PI*2);ctx.fill()}ctx.restore()}else if(b.gameType==='glass'){ctx.save();roundedBodyPath(ctx,b,b.glassWidth,b.glassHeight,4);ctx.fillStyle='rgba(170,232,250,.34)';ctx.fill();ctx.strokeStyle='rgba(235,253,255,.96)';ctx.lineWidth=4;ctx.stroke();ctx.strokeStyle='rgba(255,255,255,.55)';ctx.lineWidth=3;ctx.beginPath();ctx.moveTo(-b.glassWidth*.3,b.glassHeight*.32);ctx.lineTo(b.glassWidth*.2,-b.glassHeight*.35);ctx.stroke();ctx.restore()}else if(b.gameType==='metal'){ctx.save();roundedBodyPath(ctx,b,b.metalWidth,b.metalHeight,6);const g=ctx.createLinearGradient(0,-b.metalHeight/2,0,b.metalHeight/2);g.addColorStop(0,'#a7b0b8');g.addColorStop(.45,'#67737e');g.addColorStop(1,'#39434b');ctx.fillStyle=g;ctx.fill();ctx.strokeStyle='#252d33';ctx.lineWidth=3;ctx.stroke();ctx.restore()}else if(b.gameType==='concrete'){ctx.save();roundedBodyPath(ctx,b,b.concreteWidth,b.concreteHeight,5);ctx.fillStyle='#979c9f';ctx.fill();ctx.strokeStyle='#555d62';ctx.lineWidth=4;ctx.stroke();ctx.globalAlpha=.25;ctx.fillStyle='#4f565a';for(let i=0;i<7;i++){ctx.beginPath();ctx.arc((i%3-1)*b.concreteWidth*.2,(Math.floor(i/3)-1)*b.concreteHeight*.18,2+i%2,0,Math.PI*2);ctx.fill()}ctx.restore()}}}
function drawOfficePropsArt(ctx){for(const b of Composite.allBodies(engine.world)){if(b.gameType!=='officeProp')continue;ctx.save();ctx.translate(b.position.x,b.position.y);ctx.rotate(b.angle);if(b.propKind==='cabinet'){ctx.fillStyle='#4a5662';ctx.strokeStyle='#202932';ctx.lineWidth=4;ctx.beginPath();ctx.roundRect(-35,-69,70,138,6);ctx.fill();ctx.stroke();ctx.fillStyle='#6e7b87';ctx.fillRect(-27,-59,54,118);ctx.fillStyle='#d3dae0';ctx.beginPath();ctx.roundRect(20,-12,5,27,3);ctx.fill()}else if(b.propKind==='monitor'){ctx.fillStyle='#17232d';ctx.strokeStyle='#596875';ctx.lineWidth=4;ctx.beginPath();ctx.roundRect(-33,-24,66,48,6);ctx.fill();ctx.stroke();ctx.fillStyle='#09131b';ctx.fillRect(-26,-17,52,31);ctx.fillStyle='rgba(127,200,227,.24)';ctx.beginPath();ctx.moveTo(-24,11);ctx.lineTo(8,-17);ctx.lineTo(25,-17);ctx.lineTo(-7,11);ctx.fill();ctx.fillStyle='#4c5963';ctx.fillRect(-5,24,10,12);ctx.fillRect(-18,34,36,6)}else{ctx.fillStyle='#e5e7e8';ctx.strokeStyle='#59636a';ctx.lineWidth=4;ctx.beginPath();ctx.roundRect(-37,-26,74,52,7);ctx.fill();ctx.stroke();ctx.fillStyle='#b7bec3';ctx.fillRect(-25,-9,50,18);ctx.fillStyle='#2c3942';ctx.fillRect(-18,13,36,5);ctx.fillStyle='#fff';ctx.fillRect(-19,-35,38,18)}ctx.restore()}}
"""
s=s[:idx]+art+s[idx:]

# Render new art before damage overlays/characters.
s=s.replace("drawTrajectory(ctx);drawHeroQueue(ctx);drawSlingshot(ctx);drawWoodDamage(ctx);","drawTrajectory(ctx);drawHeroQueue(ctx);drawSlingshot(ctx);drawWorldArt(ctx);drawOfficePropsArt(ctx);drawWoodDamage(ctx);")
p.write_text(s)
