const { Engine, Render, Runner, World, Bodies, Body, Events, Composite, Constraint, Mouse, MouseConstraint, Vector } = Matter;

const $ = id => document.getElementById(id);
const canvas=$('gameCanvas'),shotsEl=$('shots'),speedEl=$('speed'),statusEl=$('status'),levelEl=$('level'),targetsEl=$('targets'),scoreEl=$('score'),starsEl=$('stars'),shotRack=$('shotRack');
const resetBtn=$('resetBtn'),debugBtn=$('debugBtn'),menuBtn=$('menuBtn'),pauseBtn=$('pauseBtn'),pausePanel=$('pausePanel'),resumeBtn=$('resumeBtn'),pauseRestartBtn=$('pauseRestartBtn'),pauseMenuBtn=$('pauseMenuBtn');
const result=$('result'),resultTitle=$('resultTitle'),resultText=$('resultText'),resultStars=$('resultStars'),nextBtn=$('nextBtn'),retryBtn=$('retryBtn'),levelMenu=$('levelMenu'),levelGrid=$('levelGrid'),totalStarsEl=$('totalStars');

const STORAGE_KEY='officeBirdsProgressV1';
const engine=Engine.create({enableSleeping:false});
engine.gravity.y=1;engine.positionIterations=12;engine.velocityIterations=10;engine.constraintIterations=6;
const render=Render.create({canvas,engine,options:{width:innerWidth,height:innerHeight,pixelRatio:Math.min(devicePixelRatio||1,2),wireframes:false,background:'transparent'}});
const runner=Runner.create({isFixed:true,delta:1000/60});

const LEVELS=[
{name:'Точная разминка',shots:2,build({x,y,beam,pillar,weakPillar,glass,target}){return[
  beam(x,y-15,290),
  pillar(x-112,y-92,122),weakPillar(x+112,y-92,122),
  glass(x,y-92,168,82),
  beam(x,y-170,300),
  pillar(x-86,y-238,106),pillar(x+86,y-238,106),
  beam(x,y-305,230),
  target(x+42,y-352)
]}},
{name:'Слабое звено',shots:3,build({x,y,beam,pillar,weakPillar,glass,metal,concrete,cabinet,monitor,printer,target}){return[
  concrete(x-150,y-48,76,64),concrete(x+150,y-48,76,64),
  beam(x,y-15,390),
  pillar(x-145,y-95,130),weakPillar(x,y-95,130),pillar(x+145,y-95,130),
  glass(x-72,y-98,88,90),glass(x+72,y-98,88,90),
  beam(x,y-178,390),
  metal(x,y-221,140,28),monitor(x-88,y-226),printer(x+82,y-228),
  pillar(x-120,y-270,110),pillar(x+120,y-270,110),cabinet(x+166,y-284),
  beam(x,y-338,300),
  target(x-82,y-388),target(x+82,y-388)
]}},
{name:'Каскад',shots:4,build({x,y,beam,pillar,weakPillar,glass,metal,concrete,cabinet,monitor,printer,target}){const l=x-190,r=x+190;return[
  concrete(l-92,y-50,74,66),beam(l,y-15,250),pillar(l-82,y-94,126),weakPillar(l+82,y-94,126),glass(l,y-98,116,90),beam(l,y-176,250),metal(l,y-218,104,28),monitor(l-52,y-230),cabinet(l+105,y-292),target(l+28,y-252),
  concrete(r+92,y-50,74,66),beam(r,y-15,250),weakPillar(r-82,y-94,126),pillar(r+82,y-94,126),glass(r,y-98,116,90),beam(r,y-176,250),metal(r,y-218,104,28),printer(r+48,y-230),cabinet(r-105,y-292),target(r-28,y-252),
  pillar(x-55,y-300,120),weakPillar(x+55,y-300,120),beam(x,y-370,560),target(x,y-420)
]}}
];

const SPRITES={heroIdle:0,heroTension:1,heroFlying:2,heroStunned:3,bossIdle:4,bossSmug:5,bossPanic:6,bossDefeated:7};
const officeBirdAtlas=new Image();
officeBirdAtlas.src='./assets/sprites/office-birds-vectors.svg';
window.officeBirdAtlas=officeBirdAtlas;
let progress=loadProgress(),levelIndex=0,ball,sling,mouseConstraint,anchor,shotsUsed=0,released=false,detached=false,respawnQueued=false,targets=[],levelFinished=false,floorY=0,levelStartTime=0,score=0,lowSpeedFrames=0,shotStartedAt=0,paused=false;
let particles=[],impactRings=[],flash=0,heroStunnedUntil=0,heroSpawnAt=0,stabilityJoints=[];
const woodDamageLedger=new Map();

function loadProgress(){try{const s=JSON.parse(localStorage.getItem(STORAGE_KEY));if(s?.levels?.length===LEVELS.length)return s}catch(_){}return{unlocked:1,levels:LEVELS.map(()=>({stars:0,bestScore:0}))}}
function saveProgress(){localStorage.setItem(STORAGE_KEY,JSON.stringify(progress))}
function remainingShots(){return Math.max(0,LEVELS[levelIndex].shots-shotsUsed)}
function activeHeroReady(){return !!(ball&&!detached&&!respawnQueued)}
function reserveHeroes(){return Math.max(0,remainingShots()-(activeHeroReady()?1:0))}
function aliveTargets(){return targets.filter(t=>!t.defeated).length}
function currentStars(){const r=remainingShots();const max=LEVELS[levelIndex].shots;return r>=Math.max(2,max-1)?3:r>=1?2:1}
function setStatus(t){statusEl.textContent=t}
function renderShotRack(){shotRack.innerHTML='';for(let i=0;i<LEVELS[levelIndex].shots;i++){const d=document.createElement('span');d.className=`shot-dot${i<shotsUsed?' used':''}`;shotRack.appendChild(d)}}
function updateHud(){levelEl.textContent=`${levelIndex+1}/${LEVELS.length} — ${LEVELS[levelIndex].name}`;shotsEl.textContent=`${remainingShots()} (${reserveHeroes()} в запасе)`;targetsEl.textContent=aliveTargets();speedEl.textContent=ball?Vector.magnitude(ball.velocity).toFixed(1):'0.0';scoreEl.textContent=score;starsEl.textContent='★'.repeat(progress.levels[levelIndex].stars)+'☆'.repeat(3-progress.levels[levelIndex].stars);renderShotRack()}

function woodRender(kind){return{visible:false}}
function setupWood(b,kind,w,h){b.gameType='structure';b.material='wood';b.woodKind=kind;b.woodWidth=w;b.woodHeight=h;b.maxHealth=kind==='beam'?105:125;b.health=b.maxHealth;b.damageState=0;b.breakable=true;b.isSupport=kind==='pillar';woodDamageLedger.set(b.id,{health:b.health,damageState:0});return b}
function makeBeam(x,y,w){return setupWood(Bodies.rectangle(x,y,w,30,{density:.0024,friction:.72,frictionStatic:.9,frictionAir:.008,restitution:.03,chamfer:{radius:7},render:woodRender('beam')}),'beam',w,30)}
function makePillar(x,y,h){return setupWood(Bodies.rectangle(x,y,34,h,{density:.0027,friction:.75,frictionStatic:.95,frictionAir:.008,restitution:.02,chamfer:{radius:5},render:woodRender('pillar')}),'pillar',34,h)}
function makeWeakPillar(x,y,h){const b=setupWood(Bodies.rectangle(x,y,30,h,{density:.0019,friction:.68,frictionStatic:.82,frictionAir:.01,restitution:.025,chamfer:{radius:4},render:{fillStyle:'#d69a45',strokeStyle:'#7a4818',lineWidth:3}}),'pillar',30,h);b.maxHealth=58;b.health=58;b.isSupport=true;b.weakPoint=true;b.render.fillStyle='#d69a45';b.render.strokeStyle='#7a4818';return b}
function makeGlass(x,y,w,h){const g=Bodies.rectangle(x,y,w,h,{density:.0007,friction:.08,frictionAir:.003,restitution:.08,render:{visible:false}});g.gameType='glass';g.material='glass';g.maxHealth=34;g.health=34;g.damageState=0;g.glassWidth=w;g.glassHeight=h;g.breakable=true;return g}
function makeGlassShard(source,x,y,size,angle){const shard=Bodies.polygon(x,y,3,size,{density:.00035,friction:.04,frictionAir:.018,restitution:.22,render:{fillStyle:'rgba(171,235,250,.42)',strokeStyle:'rgba(230,254,255,.8)',lineWidth:1}});shard.gameType='glassShard';shard.material='glass';shard.createdAt=performance.now();Body.setAngle(shard,angle);Body.setVelocity(shard,{x:source.velocity.x+(Math.random()-.5)*6,y:source.velocity.y-2-Math.random()*4});Body.setAngularVelocity(shard,(Math.random()-.5)*.45);return shard}
function breakGlass(body,contact){if(!body||body.broken)return;releaseJointsFor(body,80);body.broken=true;const count=Math.min(12,Math.max(7,Math.round((body.glassWidth*body.glassHeight)/1800))),shards=[];for(let i=0;i<count;i++){const ox=(Math.random()-.5)*body.glassWidth*.75,oy=(Math.random()-.5)*body.glassHeight*.75;shards.push(makeGlassShard(body,body.position.x+ox,body.position.y+oy,6+Math.random()*8,body.angle+Math.random()*Math.PI))}World.remove(engine.world,body);World.add(engine.world,shards);burst(contact?.x||body.position.x,contact?.y||body.position.y,20,'#d7f7ff');impactRings.push({x:contact?.x||body.position.x,y:contact?.y||body.position.y,r:6,life:18,power:6});score+=75;setStatus('Стекло разбито');updateHud()}
function damageGlass(body,power,contact){if(!body||body.material!=='glass'||body.broken)return;const damage=Math.max(0,(power-1.2)*14);if(damage<3)return;body.health=Math.max(0,body.health-damage);body.damageState=body.health<body.maxHealth*.55?1:0;if(body.damageState){body.render.fillStyle='rgba(144,213,235,.27)';body.render.strokeStyle='rgba(235,253,255,.98)';body.render.lineWidth=4}if(body.health<=0||power>4.6)breakGlass(body,contact);else{burst(contact?.x||body.position.x,contact?.y||body.position.y,5,'#e3fbff');setStatus('Стекло треснуло')}}
function drawGlassDamage(ctx){for(const b of Composite.allBodies(engine.world)){if(b.material!=='glass'||b.gameType==='glassShard'||!b.damageState||b.broken)continue;ctx.save();ctx.translate(b.position.x,b.position.y);ctx.rotate(b.angle);ctx.strokeStyle='rgba(245,255,255,.95)';ctx.lineWidth=2;ctx.beginPath();ctx.moveTo(-b.glassWidth*.08,-b.glassHeight*.45);ctx.lineTo(0,-b.glassHeight*.12);ctx.lineTo(-b.glassWidth*.18,b.glassHeight*.16);ctx.lineTo(-b.glassWidth*.03,b.glassHeight*.44);ctx.moveTo(0,-b.glassHeight*.12);ctx.lineTo(b.glassWidth*.24,-b.glassHeight*.02);ctx.moveTo(-b.glassWidth*.18,b.glassHeight*.16);ctx.lineTo(b.glassWidth*.2,b.glassHeight*.3);ctx.stroke();ctx.restore()}}
function makeMetal(x,y,w,h){const m=Bodies.rectangle(x,y,w,h,{density:.0085,friction:.62,frictionStatic:.8,frictionAir:.004,restitution:.04,chamfer:{radius:6},render:{visible:false}});m.gameType='metal';m.material='metal';m.maxHealth=160;m.health=160;m.damageState=0;m.metalWidth=w;m.metalHeight=h;return m}
function damageMetal(body,power,contact){if(!body||body.material!=='metal')return;const damage=Math.max(0,(power-4)*4);if(damage<2)return;body.health=Math.max(0,body.health-damage);body.damageState=body.health<body.maxHealth*.65?1:0;if(body.health<body.maxHealth*.3)body.damageState=2;if(body.damageState===1){body.render.fillStyle='#5e6d79';body.render.strokeStyle='#26323a'}else if(body.damageState===2){body.render.fillStyle='#4b5862';body.render.strokeStyle='#1e272e';body.render.lineWidth=5}const count=Math.min(14,4+Math.round(power));for(let i=0;i<count;i++){const a=Math.random()*Math.PI*2,s=2+Math.random()*5;particles.push({x:contact?.x||body.position.x,y:contact?.y||body.position.y,vx:Math.cos(a)*s,vy:Math.sin(a)*s-1,life:14+Math.random()*14,size:1.5+Math.random()*2.5,color:'#ffd36b'})}setStatus(body.damageState?'Металл погнут':'Удар о металл');score+=Math.min(15,Math.round(power));updateHud()}
function drawMetalDamage(ctx){for(const b of Composite.allBodies(engine.world)){if(b.material!=='metal'||!b.damageState)continue;ctx.save();ctx.translate(b.position.x,b.position.y);ctx.rotate(b.angle);ctx.strokeStyle=b.damageState===1?'rgba(30,40,48,.85)':'rgba(15,22,28,.95)';ctx.lineWidth=b.damageState===1?2.5:4;ctx.beginPath();ctx.ellipse(0,0,b.metalWidth*.16,b.metalHeight*.28,0,0,Math.PI*2);if(b.damageState>1){ctx.moveTo(-b.metalWidth*.22,-b.metalHeight*.2);ctx.lineTo(b.metalWidth*.22,b.metalHeight*.18)}ctx.stroke();ctx.restore()}}
function makeConcrete(x,y,w,h){const c=Bodies.rectangle(x,y,w,h,{density:.012,friction:.85,frictionStatic:1,frictionAir:.006,restitution:.015,chamfer:{radius:5},render:{visible:false}});c.gameType='concrete';c.material='concrete';c.maxHealth=220;c.health=220;c.damageState=0;c.concreteWidth=w;c.concreteHeight=h;c.breakable=true;return c}
function makeConcreteChunk(source,x,y,w,h){const chunk=Bodies.rectangle(x,y,w,h,{density:.009,friction:.88,frictionStatic:1,frictionAir:.012,restitution:.03,chamfer:{radius:3},render:{fillStyle:'#777d82',strokeStyle:'#42484d',lineWidth:3}});chunk.gameType='concreteChunk';chunk.material='concrete';chunk.createdAt=performance.now();Body.setAngle(chunk,source.angle+(Math.random()-.5)*.18);Body.setVelocity(chunk,{x:source.velocity.x+(Math.random()-.5)*2.4,y:source.velocity.y-1-Math.random()*1.4});Body.setAngularVelocity(chunk,(Math.random()-.5)*.12);return chunk}
function breakConcrete(body,contact){if(!body||body.broken)return;releaseJointsFor(body,110);body.broken=true;const w=body.concreteWidth,h=body.concreteHeight;const pieces=[makeConcreteChunk(body,body.position.x-w*.22,body.position.y-h*.12,w*.5,h*.58),makeConcreteChunk(body,body.position.x+w*.22,body.position.y-h*.12,w*.5,h*.58),makeConcreteChunk(body,body.position.x,body.position.y+h*.25,w*.62,h*.46)];World.remove(engine.world,body);World.add(engine.world,pieces);burst(contact?.x||body.position.x,contact?.y||body.position.y,30,'#b8b8b4');impactRings.push({x:contact?.x||body.position.x,y:contact?.y||body.position.y,r:10,life:24,power:11});score+=180;setStatus('Бетон расколот');updateHud()}
function damageConcrete(body,power,contact){if(!body||body.material!=='concrete'||body.broken)return;const damage=Math.max(0,(power-6.2)*6.2);if(damage<3)return;body.health=Math.max(0,body.health-damage);body.damageState=body.health<body.maxHealth*.7?1:0;if(body.health<body.maxHealth*.35)body.damageState=2;if(body.damageState===1){body.render.fillStyle='#7d8388';body.render.strokeStyle='#444b50'}else if(body.damageState===2){body.render.fillStyle='#696f74';body.render.strokeStyle='#343a3f';body.render.lineWidth=5}burst(contact?.x||body.position.x,contact?.y||body.position.y,Math.min(18,5+Math.round(power)),'#c6c4bd');if(body.health<=0||power>15.5)breakConcrete(body,contact);else{setStatus(body.damageState>1?'Бетон сильно повреждён':'Бетон треснул');score+=Math.min(20,Math.round(power));updateHud()}}
function drawConcreteDamage(ctx){for(const b of Composite.allBodies(engine.world)){if(b.material!=='concrete'||b.gameType==='concreteChunk'||!b.damageState||b.broken)continue;ctx.save();ctx.translate(b.position.x,b.position.y);ctx.rotate(b.angle);ctx.strokeStyle=b.damageState===1?'rgba(48,52,55,.85)':'rgba(28,31,34,.96)';ctx.lineWidth=b.damageState===1?2.5:4;ctx.beginPath();ctx.moveTo(-b.concreteWidth*.18,-b.concreteHeight*.45);ctx.lineTo(-b.concreteWidth*.03,-b.concreteHeight*.08);ctx.lineTo(-b.concreteWidth*.2,b.concreteHeight*.2);ctx.lineTo(-b.concreteWidth*.06,b.concreteHeight*.44);if(b.damageState>1){ctx.moveTo(-b.concreteWidth*.03,-b.concreteHeight*.08);ctx.lineTo(b.concreteWidth*.22,b.concreteHeight*.02);ctx.moveTo(-b.concreteWidth*.2,b.concreteHeight*.2);ctx.lineTo(b.concreteWidth*.16,b.concreteHeight*.33)}ctx.stroke();ctx.restore()}}
function setupOfficeProp(body,kind,damage,massScore){body.gameType='officeProp';body.material='office';body.propKind=kind;body.propDamage=damage;body.massScore=massScore;body.hitScored=false;return body}
function makeCabinet(x,y){return setupOfficeProp(Bodies.rectangle(x,y,70,138,{density:.0095,friction:.72,frictionStatic:.9,frictionAir:.008,restitution:.025,chamfer:{radius:5},render:{visible:false}}),'cabinet',9,120)}
function makeMonitor(x,y){return setupOfficeProp(Bodies.rectangle(x,y,66,48,{density:.0022,friction:.38,frictionAir:.01,restitution:.12,chamfer:{radius:5},render:{visible:false}}),'monitor',5.5,70)}
function makePrinter(x,y){return setupOfficeProp(Bodies.rectangle(x,y,74,52,{density:.0055,friction:.58,frictionAir:.009,restitution:.04,chamfer:{radius:7},render:{visible:false}}),'printer',7,90)}
function officePropImpact(prop,other,power,contact){if(!prop||prop.gameType!=='officeProp'||power<2.2)return;const hit=Math.max(power,prop.propDamage||0);if(other?.gameType==='target'&&hit>3.6){defeatTarget(other);setStatus(`${prop.propKind==='cabinet'?'Шкаф':prop.propKind==='printer'?'Принтер':'Монитор'} сбил менеджера`)}else if(other?.gameType==='glass'&&hit>2){damageGlass(other,hit+1.8,contact)}else if(other?.gameType==='structure'&&hit>3.2){activateStructure(other,135);damageWood(other,hit*.85,contact)}else if(other?.gameType==='concrete'&&hit>7){activateStructure(other,110);damageConcrete(other,hit*.72,contact)}else if(other?.gameType==='metal'&&hit>5){activateStructure(other,105);damageMetal(other,hit*.7,contact)}if(!prop.hitScored&&power>3){prop.hitScored=true;score+=prop.massScore||50;burst(contact?.x||prop.position.x,contact?.y||prop.position.y,8,prop.propKind==='monitor'?'#a7efff':'#d5d8dc');updateHud()}}
function makeTarget(x,y){const t=Bodies.circle(x,y,27,{density:.0014,friction:.28,restitution:.08,render:{visible:false}});t.gameType='target';t.defeated=false;t.start={x,y};t.variant=targets.length%2;targets.push(t);return t}
function isStructuralBody(b){return ['structure','glass','metal','concrete','officeProp'].includes(b?.gameType)}
function freezeStructure(bodies){stabilityJoints=[];for(const b of bodies){if(isStructuralBody(b)){Body.setStatic(b,true);b.structureFrozen=true}}}
function activateStructure(body,radius=95){if(!body)return;for(const b of Composite.allBodies(engine.world)){if(!isStructuralBody(b)||!b.isStatic)continue;const near=b===body||Vector.magnitude(Vector.sub(b.position,body.position))<=radius;if(near){Body.setStatic(b,false);b.structureFrozen=false;Body.setVelocity(b,{x:b.velocity.x,y:b.velocity.y+.15})}}}
function releaseJointsFor(body,radius=0){activateStructure(body,radius||95)}

function createProjectile(){heroSpawnAt=performance.now();ball=Bodies.circle(anchor.x,anchor.y,34,{density:.004,restitution:.35,friction:.12,frictionAir:.004,render:{visible:false}});ball.gameType='projectile';ball.launchCounted=false;sling=Constraint.create({pointA:anchor,bodyB:ball,stiffness:.018,damping:.035,length:0,render:{visible:false}});World.add(engine.world,[ball,sling]);released=false;detached=false;respawnQueued=false;lowSpeedFrames=0;shotStartedAt=0;heroStunnedUntil=0;if(!levelFinished)setStatus('Потяни героя назад')}
function setupMouse(){if(mouseConstraint){Events.off(mouseConstraint);if(mouseConstraint.mouse&&Mouse.clearSourceEvents)Mouse.clearSourceEvents(mouseConstraint.mouse);World.remove(engine.world,mouseConstraint);mouseConstraint=null}const mouse=Mouse.create(canvas);mouse.pixelRatio=render.options.pixelRatio;mouseConstraint=MouseConstraint.create(engine,{mouse,constraint:{stiffness:.18,damping:.12,render:{visible:false}}});Events.on(mouseConstraint,'startdrag',e=>{if(paused||levelFinished||e.body!==ball||detached||ball?.launchCounted)return;released=false;setStatus('Натяжение')});Events.on(mouseConstraint,'enddrag',e=>{if(paused||levelFinished||e.body!==ball||detached||ball?.launchCounted)return;const stretch=Vector.magnitude(Vector.sub(ball.position,anchor));if(stretch<45){setStatus('Потяни сильнее');return}ball.launchCounted=true;released=true;shotsUsed=Math.min(LEVELS[levelIndex].shots,shotsUsed+1);shotStartedAt=performance.now();setStatus('Запуск');updateHud()});World.add(engine.world,mouseConstraint);render.mouse=mouse}

function loadLevel(index){stabilityJoints=[];woodDamageLedger.clear();paused=false;engine.timing.timeScale=1;pausePanel.classList.remove('show');pauseBtn.textContent='Пауза';levelIndex=Math.max(0,Math.min(index,LEVELS.length-1));Composite.clear(engine.world,false);targets=[];particles=[];impactRings=[];shotsUsed=0;score=0;levelFinished=false;result.classList.remove('show');levelMenu.classList.remove('show');floorY=innerHeight-110;anchor={x:Math.max(320,innerWidth*.21),y:floorY-210};const towerX=Math.max(innerWidth*.72,anchor.x+650);World.add(engine.world,Bodies.rectangle(innerWidth/2,floorY+45,innerWidth+500,90,{isStatic:true,friction:1,render:{fillStyle:'#283846',strokeStyle:'#17232d',lineWidth:2}}));createProjectile();const levelBodies=LEVELS[levelIndex].build({x:towerX,y:floorY,beam:makeBeam,pillar:makePillar,weakPillar:makeWeakPillar,glass:makeGlass,metal:makeMetal,concrete:makeConcrete,cabinet:makeCabinet,monitor:makeMonitor,printer:makePrinter,target:makeTarget});World.add(engine.world,levelBodies);freezeStructure(levelBodies);setupMouse();levelStartTime=performance.now();updateHud()}
function queueProjectile(){if(respawnQueued||levelFinished)return;syncWoodDamage();respawnQueued=true;setStatus(reserveHeroes()>0?'Следующий герой через секунду…':'Последний бросок завершён');setTimeout(()=>{if(levelFinished)return;if(ball)World.remove(engine.world,ball);if(sling)World.remove(engine.world,sling);ball=null;sling=null;if(aliveTargets()===0){finishLevel(true);return}if(remainingShots()>0){createProjectile();setStatus('Следующий герой готов')}else{finishLevel(false)}},1100)}
function defeatTarget(t){if(!t||t.defeated)return;t.defeated=true;t.defeatedAt=performance.now();score+=100;burst(t.position.x,t.position.y,16,'#f7c56d');updateHud();if(aliveTargets()===0){setStatus('Все менеджеры сбиты');setTimeout(()=>finishLevel(true),1200)}}
function finishLevel(won){if(levelFinished)return;levelFinished=true;if(won){const stars=currentStars(),timeBonus=Math.max(0,Math.round(300-(performance.now()-levelStartTime)/100)),finalScore=score+remainingShots()*250+timeBonus;score=finalScore;const rec=progress.levels[levelIndex];rec.stars=Math.max(rec.stars,stars);rec.bestScore=Math.max(rec.bestScore,finalScore);progress.unlocked=Math.max(progress.unlocked,Math.min(LEVELS.length,levelIndex+2));saveProgress();resultTitle.textContent='Уровень пройден!';resultStars.textContent='★'.repeat(stars)+'☆'.repeat(3-stars);resultText.textContent=`Счёт: ${finalScore}. Осталось героев: ${remainingShots()}.`;nextBtn.hidden=false;nextBtn.textContent=levelIndex===LEVELS.length-1?'К уровням':'Следующий уровень';setStatus('Уровень пройден')}else{resultTitle.textContent='Попробуй ещё раз';resultStars.textContent='☆☆☆';resultText.textContent=`Осталось менеджеров: ${aliveTargets()}.`;nextBtn.hidden=true;setStatus('Герои закончились')}updateHud();result.classList.add('show')}

function renderLevelMenu(){const total=progress.levels.reduce((s,l)=>s+l.stars,0);totalStarsEl.textContent=`${total}/${LEVELS.length*3}`;levelGrid.innerHTML='';LEVELS.forEach((l,i)=>{const unlocked=i<progress.unlocked,rec=progress.levels[i],btn=document.createElement('button');btn.className='level-tile';btn.disabled=!unlocked;btn.innerHTML=`<span class="level-number">${i+1}</span><strong>${l.name}</strong><span class="level-stars">${unlocked?'★'.repeat(rec.stars)+'☆'.repeat(3-rec.stars):'🔒'}</span><small>${rec.bestScore?`Рекорд: ${rec.bestScore}`:'Не пройден'}</small>`;btn.onclick=()=>loadLevel(i);levelGrid.appendChild(btn)})}
function showMenu(){paused=true;engine.timing.timeScale=0;pausePanel.classList.remove('show');renderLevelMenu();levelMenu.classList.add('show');result.classList.remove('show')}
function togglePause(force){if(levelFinished||levelMenu.classList.contains('show'))return;paused=typeof force==='boolean'?force:!paused;engine.timing.timeScale=paused?0:1;pausePanel.classList.toggle('show',paused);pauseBtn.textContent=paused?'Продолжить':'Пауза'}

function burst(x,y,count,color){for(let i=0;i<count;i++){const a=Math.random()*Math.PI*2,s=1.5+Math.random()*4;particles.push({x,y,vx:Math.cos(a)*s,vy:Math.sin(a)*s-1,life:28+Math.random()*22,size:2+Math.random()*5,color})}}
function impact(x,y,power){impactRings.push({x,y,r:8,life:18,power});flash=Math.max(flash,Math.min(.18,power/90));burst(x,y,Math.min(22,6+Math.round(power)),'#d9a15f')}
function updateEffects(){for(const p of particles){p.x+=p.vx;p.y+=p.vy;p.vy+=.15;p.vx*=.98;p.life--}particles=particles.filter(p=>p.life>0);for(const r of impactRings){r.r+=3+r.power*.08;r.life--}impactRings=impactRings.filter(r=>r.life>0);flash*=.82}
function updateWoodLook(body){const ratio=Math.max(0,body.health/body.maxHealth);const next=ratio>.66?0:ratio>.32?1:2;body.damageState=next;if(next===0){body.render.fillStyle=body.woodKind==='beam'?'#c9823c':'#a95d2b';body.render.strokeStyle=body.woodKind==='beam'?'#6f3b18':'#5a2f16';body.render.lineWidth=3}else if(next===1){body.render.fillStyle=body.woodKind==='beam'?'#b96f31':'#965025';body.render.strokeStyle='#54270f';body.render.lineWidth=3}else{body.render.fillStyle=body.woodKind==='beam'?'#8e4e25':'#713918';body.render.strokeStyle='#321507';body.render.lineWidth=4}woodDamageLedger.set(body.id,{health:body.health,damageState:body.damageState})}
function syncWoodDamage(){for(const b of Composite.allBodies(engine.world)){if(b.material!=='wood'||b.broken)continue;const saved=woodDamageLedger.get(b.id);if(saved){b.health=saved.health;b.damageState=saved.damageState}updateWoodLook(b)}}
function makeWoodFragment(source,x,y,w,h){const piece=Bodies.rectangle(x,y,w,h,{density:.0021,friction:.72,frictionStatic:.9,frictionAir:.012,restitution:.08,chamfer:{radius:4},render:{fillStyle:source.render.fillStyle,strokeStyle:'#3b1b0c',lineWidth:3}});piece.gameType='debris';piece.material='wood';piece.createdAt=performance.now();Body.setAngle(piece,source.angle);Body.setVelocity(piece,{x:source.velocity.x+(Math.random()-.5)*2.5,y:source.velocity.y-1-Math.random()*1.5});Body.setAngularVelocity(piece,source.angularVelocity+(Math.random()-.5)*.18);return piece}
function breakWood(body,contact){if(!body||body.broken||!body.breakable)return;releaseJointsFor(body,body.weakPoint?190:0);body.broken=true;const horizontal=body.woodKind==='beam',gap=5,partW=horizontal?(body.woodWidth-gap)/2:body.woodWidth,partH=horizontal?body.woodHeight:(body.woodHeight-gap)/2;const local=horizontal?{x:body.woodWidth*.26,y:0}:{x:0,y:body.woodHeight*.26};const c=Math.cos(body.angle),si=Math.sin(body.angle),offset={x:local.x*c-local.y*si,y:local.x*si+local.y*c};const a=makeWoodFragment(body,body.position.x-offset.x,body.position.y-offset.y,partW,partH),b=makeWoodFragment(body,body.position.x+offset.x,body.position.y+offset.y,partW,partH);World.remove(engine.world,body);World.add(engine.world,[a,b]);burst(contact?.x||body.position.x,contact?.y||body.position.y,18,'#c78342');impactRings.push({x:contact?.x||body.position.x,y:contact?.y||body.position.y,r:8,life:22,power:8});score+=body.weakPoint?400:(body.isSupport?250:100);setStatus(body.weakPoint?'Слабая опора выбита!':(body.isSupport?'Несущая опора сломана':'Дерево раскололось'));updateHud()}
function damageWood(body,power,contact){if(!body||body.material!=='wood'||!body.breakable||body.broken)return;const saved=woodDamageLedger.get(body.id);if(saved)body.health=saved.health;const damage=Math.max(0,(power-2.2)*10.5);if(damage<4)return;body.health=Math.max(0,body.health-damage);updateWoodLook(body);burst(contact?.x||body.position.x,contact?.y||body.position.y,Math.min(10,3+Math.round(damage/9)),'#d6a065');if(body.health<=0||power>11.5)breakWood(body,contact)}
function drawWoodDamage(ctx){for(const b of Composite.allBodies(engine.world)){if(b.material!=='wood'||!b.damageState||b.broken)continue;ctx.save();ctx.translate(b.position.x,b.position.y);ctx.rotate(b.angle);ctx.strokeStyle=b.damageState===1?'rgba(55,26,10,.75)':'rgba(35,12,4,.95)';ctx.lineWidth=b.damageState===1?2:3;const w=b.woodWidth,h=b.woodHeight;ctx.beginPath();if(b.woodKind==='beam'){ctx.moveTo(-w*.18,-h*.45);ctx.lineTo(-w*.08,0);ctx.lineTo(-w*.15,h*.45);if(b.damageState>1){ctx.moveTo(w*.12,-h*.45);ctx.lineTo(w*.03,-2);ctx.lineTo(w*.18,h*.45)}}else{ctx.moveTo(-w*.45,-h*.18);ctx.lineTo(0,-h*.06);ctx.lineTo(w*.45,-h*.14);if(b.damageState>1){ctx.moveTo(-w*.45,h*.12);ctx.lineTo(2,h*.03);ctx.lineTo(w*.45,h*.18)}}ctx.stroke();ctx.restore()}}

function atlasReady(){const a=window.officeBirdAtlas;return a&&a.complete&&a.naturalWidth>0}
function drawSprite(ctx,index,x,y,w,h,angle=0){if(!atlasReady())return false;const a=window.officeBirdAtlas,cols=4,rows=2,sw=a.naturalWidth/cols,sh=a.naturalHeight/rows,sx=(index%cols)*sw,sy=Math.floor(index/cols)*sh;ctx.save();ctx.translate(x,y);ctx.rotate(angle);ctx.shadowColor='rgba(0,0,0,.28)';ctx.shadowBlur=10;ctx.shadowOffsetY=6;ctx.drawImage(a,sx,sy,sw,sh,-w/2,-h/2,w,h);ctx.restore();return true}
function drawFallbackHero(ctx){const{x,y}=ball.position;ctx.save();ctx.translate(x,y);ctx.rotate(ball.angle);ctx.fillStyle='#26364a';ctx.beginPath();ctx.arc(0,0,32,0,Math.PI*2);ctx.fill();ctx.fillStyle='#f1c7a4';ctx.beginPath();ctx.arc(4,-8,13,0,Math.PI*2);ctx.fill();ctx.restore()}
function drawFallbackBoss(ctx,t){ctx.save();ctx.translate(t.position.x,t.position.y);ctx.rotate(t.angle);ctx.fillStyle=t.defeated?'#727b86':'#2b3543';ctx.fillRect(-20,-20,40,55);ctx.fillStyle='#e9bf9d';ctx.beginPath();ctx.arc(0,-25,16,0,Math.PI*2);ctx.fill();ctx.restore()}

function drawBackground(ctx){const w=render.canvas.width,h=render.canvas.height,pr=render.options.pixelRatio||1;ctx.save();ctx.setTransform(1,0,0,1,0,0);const floor=(floorY-4)*pr;const wall=ctx.createLinearGradient(0,0,0,floor);wall.addColorStop(0,'#dfe9f5');wall.addColorStop(.58,'#f7fbff');wall.addColorStop(1,'#e9dfd0');ctx.fillStyle=wall;ctx.fillRect(0,0,w,floor);ctx.fillStyle='#cad3df';ctx.fillRect(0,0,w,74*pr);ctx.strokeStyle='rgba(80,98,120,.18)';ctx.lineWidth=2*pr;for(let x=0;x<w;x+=160*pr){ctx.beginPath();ctx.moveTo(x,0);ctx.lineTo(x,74*pr);ctx.stroke()}ctx.fillStyle='#fff2cf';ctx.shadowColor='rgba(255,220,150,.5)';ctx.shadowBlur=28*pr;ctx.fillRect(w*.77,17*pr,170*pr,34*pr);ctx.shadowBlur=0;const wx=w*.29,wy=115*pr,ww=w*.62,wh=Math.max(250*pr,floor-wy-85*pr);ctx.fillStyle='#a9d9f4';ctx.fillRect(wx,wy,ww,wh);const sky=ctx.createLinearGradient(0,wy,0,wy+wh);sky.addColorStop(0,'#79c8f3');sky.addColorStop(1,'#dff3ff');ctx.fillStyle=sky;ctx.fillRect(wx,wy,ww,wh);ctx.globalAlpha=.42;for(let i=0;i<13;i++){const bw=(34+(i%4)*14)*pr,bh=(95+(i%5)*43)*pr,x=wx+i*(ww/12)-10*pr,y=wy+wh-bh;ctx.fillStyle=i%2?'#75a9c3':'#8ab7cb';ctx.fillRect(x,y,bw,bh);ctx.fillStyle='rgba(244,248,220,.5)';for(let yy=y+14*pr;yy<y+bh-8*pr;yy+=23*pr)for(let xx=x+8*pr;xx<x+bw-6*pr;xx+=15*pr)ctx.fillRect(xx,yy,5*pr,8*pr)}ctx.globalAlpha=1;ctx.strokeStyle='#7f94a8';ctx.lineWidth=8*pr;ctx.strokeRect(wx,wy,ww,wh);for(let i=1;i<4;i++){ctx.beginPath();ctx.moveTo(wx+ww*i/4,wy);ctx.lineTo(wx+ww*i/4,wy+wh);ctx.stroke()}ctx.fillStyle='#e8dfd2';ctx.fillRect(0,floor-76*pr,w,76*pr);ctx.fillStyle='#9b6b42';ctx.fillRect(0,floor,w,h-floor);ctx.fillStyle='#704627';ctx.fillRect(0,floor,w,13*pr);ctx.strokeStyle='rgba(77,44,23,.26)';ctx.lineWidth=2*pr;for(let x=0;x<w;x+=130*pr){ctx.beginPath();ctx.moveTo(x,floor);ctx.lineTo(x+18*pr,h);ctx.stroke()}ctx.fillStyle='rgba(255,255,255,.22)';ctx.fillRect(0,floor-7*pr,w,7*pr);ctx.restore()}
function drawSlingshot(ctx){ctx.save();ctx.lineCap='round';ctx.lineJoin='round';ctx.shadowColor='rgba(35,18,8,.35)';ctx.shadowBlur=18;ctx.shadowOffsetY=10;const grad=ctx.createLinearGradient(anchor.x-55,anchor.y,anchor.x+55,floorY);grad.addColorStop(0,'#7b3c18');grad.addColorStop(.45,'#c57932');grad.addColorStop(1,'#6e3518');ctx.strokeStyle=grad;ctx.lineWidth=30;ctx.beginPath();ctx.moveTo(anchor.x,floorY-7);ctx.lineTo(anchor.x,anchor.y+18);ctx.moveTo(anchor.x,anchor.y+25);ctx.lineTo(anchor.x-53,anchor.y-50);ctx.moveTo(anchor.x,anchor.y+25);ctx.lineTo(anchor.x+53,anchor.y-50);ctx.stroke();ctx.shadowBlur=0;ctx.strokeStyle='#e8a050';ctx.lineWidth=6;ctx.beginPath();ctx.moveTo(anchor.x-6,floorY-16);ctx.lineTo(anchor.x-6,anchor.y+14);ctx.stroke();ctx.fillStyle='#8b4c24';ctx.strokeStyle='#3d2113';ctx.lineWidth=4;ctx.beginPath();ctx.roundRect(anchor.x-72,floorY-4,144,28,8);ctx.fill();ctx.stroke();ctx.fillStyle='#4b5660';for(const x of [anchor.x-42,anchor.x+42]){ctx.beginPath();ctx.arc(x,floorY+10,6,0,Math.PI*2);ctx.fill()}if(!detached&&ball){ctx.strokeStyle='#332016';ctx.lineWidth=8;ctx.beginPath();ctx.moveTo(anchor.x-53,anchor.y-50);ctx.lineTo(ball.position.x,ball.position.y);ctx.lineTo(anchor.x+53,anchor.y-50);ctx.stroke()}ctx.restore()}
function drawHeroQueue(ctx){const waiting=reserveHeroes();if(!waiting)return;const spacing=58,startX=Math.max(70,anchor.x-120-(waiting-1)*spacing),y=floorY-42;for(let i=0;i<waiting;i++){const x=startX+i*spacing;if(!drawSprite(ctx,SPRITES.heroIdle,x,y,52,64,0)){ctx.save();ctx.fillStyle='#26364a';ctx.beginPath();ctx.arc(x,y-5,18,0,Math.PI*2);ctx.fill();ctx.restore()}ctx.save();ctx.fillStyle='rgba(0,0,0,.18)';ctx.beginPath();ctx.ellipse(x,floorY-8,22,5,0,0,Math.PI*2);ctx.fill();ctx.restore()}}
function roundedBodyPath(ctx,b,w,h,r=7){ctx.translate(b.position.x,b.position.y);ctx.rotate(b.angle);ctx.beginPath();ctx.roundRect(-w/2,-h/2,w,h,r)}
function drawWorldArt(ctx){for(const b of Composite.allBodies(engine.world)){if(b.gameType==='structure'){ctx.save();roundedBodyPath(ctx,b,b.woodWidth,b.woodHeight,7);const g=ctx.createLinearGradient(-b.woodWidth/2,0,b.woodWidth/2,0);g.addColorStop(0,b.weakPoint?'#dba04b':'#9a4f20');g.addColorStop(.42,b.weakPoint?'#f4bd65':'#d88a3d');g.addColorStop(1,b.weakPoint?'#b76b22':'#804018');ctx.fillStyle=g;ctx.shadowColor='rgba(45,22,8,.32)';ctx.shadowBlur=8;ctx.shadowOffsetY=5;ctx.fill();ctx.shadowBlur=0;ctx.strokeStyle='#5a2c14';ctx.lineWidth=3;ctx.stroke();ctx.strokeStyle='rgba(255,214,143,.45)';ctx.lineWidth=2;ctx.beginPath();ctx.moveTo(-b.woodWidth*.35,-b.woodHeight*.18);ctx.lineTo(b.woodWidth*.3,-b.woodHeight*.18);ctx.stroke();ctx.fillStyle='#4d5660';for(const x of [-b.woodWidth*.39,b.woodWidth*.39]){ctx.beginPath();ctx.arc(x,0,4,0,Math.PI*2);ctx.fill()}ctx.restore()}else if(b.gameType==='glass'){ctx.save();roundedBodyPath(ctx,b,b.glassWidth,b.glassHeight,4);ctx.fillStyle='rgba(170,232,250,.34)';ctx.fill();ctx.strokeStyle='rgba(235,253,255,.96)';ctx.lineWidth=4;ctx.stroke();ctx.strokeStyle='rgba(255,255,255,.55)';ctx.lineWidth=3;ctx.beginPath();ctx.moveTo(-b.glassWidth*.3,b.glassHeight*.32);ctx.lineTo(b.glassWidth*.2,-b.glassHeight*.35);ctx.stroke();ctx.restore()}else if(b.gameType==='metal'){ctx.save();roundedBodyPath(ctx,b,b.metalWidth,b.metalHeight,6);const g=ctx.createLinearGradient(0,-b.metalHeight/2,0,b.metalHeight/2);g.addColorStop(0,'#a7b0b8');g.addColorStop(.45,'#67737e');g.addColorStop(1,'#39434b');ctx.fillStyle=g;ctx.fill();ctx.strokeStyle='#252d33';ctx.lineWidth=3;ctx.stroke();ctx.restore()}else if(b.gameType==='concrete'){ctx.save();roundedBodyPath(ctx,b,b.concreteWidth,b.concreteHeight,5);ctx.fillStyle='#979c9f';ctx.fill();ctx.strokeStyle='#555d62';ctx.lineWidth=4;ctx.stroke();ctx.globalAlpha=.25;ctx.fillStyle='#4f565a';for(let i=0;i<7;i++){ctx.beginPath();ctx.arc((i%3-1)*b.concreteWidth*.2,(Math.floor(i/3)-1)*b.concreteHeight*.18,2+i%2,0,Math.PI*2);ctx.fill()}ctx.restore()}}}
function drawOfficePropsArt(ctx){for(const b of Composite.allBodies(engine.world)){if(b.gameType!=='officeProp')continue;ctx.save();ctx.translate(b.position.x,b.position.y);ctx.rotate(b.angle);if(b.propKind==='cabinet'){ctx.fillStyle='#4a5662';ctx.strokeStyle='#202932';ctx.lineWidth=4;ctx.beginPath();ctx.roundRect(-35,-69,70,138,6);ctx.fill();ctx.stroke();ctx.fillStyle='#6e7b87';ctx.fillRect(-27,-59,54,118);ctx.fillStyle='#d3dae0';ctx.beginPath();ctx.roundRect(20,-12,5,27,3);ctx.fill()}else if(b.propKind==='monitor'){ctx.fillStyle='#17232d';ctx.strokeStyle='#596875';ctx.lineWidth=4;ctx.beginPath();ctx.roundRect(-33,-24,66,48,6);ctx.fill();ctx.stroke();ctx.fillStyle='#09131b';ctx.fillRect(-26,-17,52,31);ctx.fillStyle='rgba(127,200,227,.24)';ctx.beginPath();ctx.moveTo(-24,11);ctx.lineTo(8,-17);ctx.lineTo(25,-17);ctx.lineTo(-7,11);ctx.fill();ctx.fillStyle='#4c5963';ctx.fillRect(-5,24,10,12);ctx.fillRect(-18,34,36,6)}else{ctx.fillStyle='#e5e7e8';ctx.strokeStyle='#59636a';ctx.lineWidth=4;ctx.beginPath();ctx.roundRect(-37,-26,74,52,7);ctx.fill();ctx.stroke();ctx.fillStyle='#b7bec3';ctx.fillRect(-25,-9,50,18);ctx.fillStyle='#2c3942';ctx.fillRect(-18,13,36,5);ctx.fillStyle='#fff';ctx.fillRect(-19,-35,38,18)}ctx.restore()}}
function drawHero(ctx){if(!ball)return;let sprite=SPRITES.heroIdle,w=116,h=116,angle=ball.angle;if(mouseConstraint?.body===ball&&!detached){const stretch=Vector.magnitude(Vector.sub(ball.position,anchor));if(stretch>30){sprite=SPRITES.heroTension;w=150;h=125;angle=0}}else if(detached){sprite=performance.now()<heroStunnedUntil?SPRITES.heroStunned:SPRITES.heroFlying;w=sprite===SPRITES.heroStunned?125:130;h=sprite===SPRITES.heroStunned?110:118}const spawnProgress=Math.min(1,(performance.now()-heroSpawnAt)/360),scale=.72+.28*(1-Math.pow(1-spawnProgress,3));w*=scale;h*=scale;if(!drawSprite(ctx,sprite,ball.position.x,ball.position.y,w,h,angle))drawFallbackHero(ctx)}
function drawTargets(ctx){for(const t of targets){const moved=Vector.magnitude(Vector.sub(t.position,t.start));let sprite=t.variant?SPRITES.bossSmug:SPRITES.bossIdle;if(t.defeated)sprite=SPRITES.bossDefeated;else if(moved>20||Math.abs(t.angle)>.22)sprite=SPRITES.bossPanic;const w=t.defeated?112:100,h=t.defeated?90:112;if(!drawSprite(ctx,sprite,t.position.x,t.position.y,w,h,t.angle))drawFallbackBoss(ctx,t)}}
function drawTrajectory(ctx){if(!mouseConstraint?.body||mouseConstraint.body!==ball||detached||paused)return;const pull=Vector.sub(anchor,ball.position),distance=Vector.magnitude(pull);if(distance<25)return;let p={...ball.position},v=Vector.mult(Vector.normalise(pull),Math.min(distance,320)*.125);const g=.278;ctx.save();for(let i=0;i<34;i++){p.x+=v.x;p.y+=v.y;v.y+=g;if(i%2)continue;ctx.beginPath();ctx.fillStyle=`rgba(255,230,132,${.92-i/45})`;ctx.arc(p.x,p.y,4.5,0,Math.PI*2);ctx.fill()}ctx.restore()}
function drawEffects(ctx){ctx.save();for(const r of impactRings){ctx.globalAlpha=r.life/18;ctx.strokeStyle='#ffe08a';ctx.lineWidth=3;ctx.beginPath();ctx.arc(r.x,r.y,r.r,0,Math.PI*2);ctx.stroke()}for(const p of particles){ctx.globalAlpha=Math.min(1,p.life/18);ctx.fillStyle=p.color;ctx.beginPath();ctx.arc(p.x,p.y,p.size,0,Math.PI*2);ctx.fill()}ctx.restore();if(flash>0){ctx.save();ctx.setTransform(1,0,0,1,0,0);ctx.fillStyle=`rgba(255,239,178,${flash})`;ctx.fillRect(0,0,render.canvas.width,render.canvas.height);ctx.restore()}}

Events.on(engine,'collisionStart',event=>{for(const pair of event.pairs){const a=pair.bodyA,b=pair.bodyB,rvAll=Vector.sub(a.velocity,b.velocity),nAll=pair.collision?.normal||{x:1,y:0},pAll=Math.abs(Vector.dot(rvAll,nAll));const contactAll=pair.collision?.supports?.[0]||{x:(a.position.x+b.position.x)/2,y:(a.position.y+b.position.y)/2};if(a.gameType==='officeProp')officePropImpact(a,b,pAll,contactAll);if(b.gameType==='officeProp')officePropImpact(b,a,pAll,contactAll);if(pAll>2.8){if(isStructuralBody(a)&&a.isStatic&&isStructuralBody(b)&&!b.isStatic)activateStructure(a,90);if(isStructuralBody(b)&&b.isStatic&&isStructuralBody(a)&&!a.isStatic)activateStructure(b,90)}if(pair.bodyA!==ball&&pair.bodyB!==ball)continue;const other=pair.bodyA===ball?pair.bodyB:pair.bodyA,rv=Vector.sub(pair.bodyA.velocity,pair.bodyB.velocity),normal=pair.collision?.normal||{x:1,y:0},power=Math.abs(Vector.dot(rv,normal));if(isStructuralBody(other)&&power>2.1)activateStructure(other,other.weakPoint?220:115);if(power>2.2){const c=pair.collision?.supports?.[0]||other.position;impact(c.x,c.y,power);heroStunnedUntil=performance.now()+Math.min(900,250+power*45)}if(other.gameType==='target'&&power>2.2){defeatTarget(other);setStatus('Менеджер выбит')}else if(other.gameType==='glass'&&power>1.2){const c=pair.collision?.supports?.[0]||other.position;damageGlass(other,power,c);score+=Math.min(18,Math.round(power*2));updateHud()}else if(other.gameType==='metal'&&power>3.2){const c=pair.collision?.supports?.[0]||other.position;damageMetal(other,power,c)}else if(other.gameType==='concrete'&&power>5.5){const c=pair.collision?.supports?.[0]||other.position;damageConcrete(other,power,c)}else if(other.gameType==='structure'&&power>2.5){const c=pair.collision?.supports?.[0]||other.position;damageWood(other,power,c);score+=Math.min(25,Math.round(power));if(!other.broken)setStatus(other.damageState?'Дерево повреждено':'Сильный удар');updateHud()}}});
Events.on(engine,'beforeUpdate',()=>{syncWoodDamage();if(!ball)return;if(released&&!detached&&sling){const offset=Vector.sub(ball.position,anchor),distance=Vector.magnitude(offset),toward=Vector.dot(ball.velocity,Vector.normalise(Vector.mult(offset,-1)));if(distance<48&&toward>1.2){World.remove(engine.world,sling);sling=null;detached=true;released=false;setStatus('Полёт')}}for(const t of targets){if(t.defeated)continue;const moved=Vector.magnitude(Vector.sub(t.position,t.start));if(shotStartedAt&&(t.position.y>floorY-36||moved>115||Math.abs(t.angle)>1.1))defeatTarget(t)}for(const b of Composite.allBodies(engine.world)){if(b.gameType==='glassShard'&&performance.now()-b.createdAt>4200)World.remove(engine.world,b)}if(detached&&!respawnQueued){const speed=Vector.magnitude(ball.velocity);lowSpeedFrames=speed<.75?lowSpeedFrames+1:0;const outside=ball.position.x>innerWidth+220||ball.position.x<-220||ball.position.y>innerHeight+260,timeout=shotStartedAt&&performance.now()-shotStartedAt>3800;if(outside||lowSpeedFrames>30||timeout)queueProjectile()}updateEffects();updateHud()});
Events.on(render,'beforeRender',()=>drawBackground(render.context));
Events.on(render,'afterRender',()=>{if(!anchor)return;const ctx=render.context;drawTrajectory(ctx);drawHeroQueue(ctx);drawSlingshot(ctx);drawWorldArt(ctx);drawOfficePropsArt(ctx);drawWoodDamage(ctx);drawGlassDamage(ctx);drawMetalDamage(ctx);drawConcreteDamage(ctx);drawTargets(ctx);drawHero(ctx);drawEffects(ctx)});

resetBtn.onclick=()=>loadLevel(levelIndex);debugBtn.onclick=()=>{render.options.wireframes=!render.options.wireframes;debugBtn.textContent=render.options.wireframes?'Debug ON':'Debug'};menuBtn.onclick=showMenu;pauseBtn.onclick=()=>togglePause();resumeBtn.onclick=()=>togglePause(false);pauseRestartBtn.onclick=()=>loadLevel(levelIndex);pauseMenuBtn.onclick=showMenu;retryBtn.onclick=()=>loadLevel(levelIndex);nextBtn.onclick=()=>levelIndex===LEVELS.length-1?showMenu():loadLevel(levelIndex+1);$('closeMenuBtn').onclick=()=>{levelMenu.classList.remove('show');paused=false;engine.timing.timeScale=1};
window.addEventListener('keydown',e=>{if(e.key.toLowerCase()==='r')loadLevel(levelIndex);if(e.key==='Escape')togglePause();if(e.code==='Space'){e.preventDefault();togglePause()}});window.addEventListener('resize',()=>loadLevel(levelIndex));
Render.run(render);Runner.run(runner,engine);loadLevel(0);renderLevelMenu();showMenu();
