const { Engine, Render, Runner, World, Bodies, Events, Composite, Constraint, Mouse, MouseConstraint, Vector } = Matter;

const $ = id => document.getElementById(id);
const canvas=$('gameCanvas'),shotsEl=$('shots'),speedEl=$('speed'),statusEl=$('status'),levelEl=$('level'),targetsEl=$('targets'),scoreEl=$('score'),starsEl=$('stars'),shotRack=$('shotRack');
const resetBtn=$('resetBtn'),debugBtn=$('debugBtn'),menuBtn=$('menuBtn'),pauseBtn=$('pauseBtn'),pausePanel=$('pausePanel'),resumeBtn=$('resumeBtn'),pauseRestartBtn=$('pauseRestartBtn'),pauseMenuBtn=$('pauseMenuBtn');
const result=$('result'),resultTitle=$('resultTitle'),resultText=$('resultText'),resultStars=$('resultStars'),nextBtn=$('nextBtn'),retryBtn=$('retryBtn'),levelMenu=$('levelMenu'),levelGrid=$('levelGrid'),totalStarsEl=$('totalStars');

const STORAGE_KEY='officeBirdsProgressV1';
const engine=Engine.create({enableSleeping:false});
engine.gravity.y=1;engine.positionIterations=12;engine.velocityIterations=10;engine.constraintIterations=6;
const render=Render.create({canvas,engine,options:{width:innerWidth,height:innerHeight,pixelRatio:Math.min(devicePixelRatio||1,2),wireframes:false,background:'transparent'}});
const runner=Runner.create({isFixed:true,delta:1000/60});

const LEVELS=[
{name:'Разминка',shots:3,build({x,y,beam,pillar,target}){return[beam(x,y-15,260),pillar(x-92,y-90,120),pillar(x+92,y-90,120),beam(x,y-165,260),target(x,y-215)]}},
{name:'Две цели',shots:4,build({x,y,beam,pillar,target}){return[beam(x,y-15,300),pillar(x-108,y-90,120),pillar(x+108,y-90,120),beam(x,y-165,300),pillar(x-108,y-240,120),pillar(x+108,y-240,120),beam(x,y-315,300),target(x-72,y-365),target(x+72,y-365)]}},
{name:'Двойная башня',shots:5,build({x,y,beam,pillar,target}){const l=x-150,r=x+150;return[beam(l,y-15,220),pillar(l-72,y-90,120),pillar(l+72,y-90,120),beam(l,y-165,220),target(l,y-215),beam(r,y-15,220),pillar(r-72,y-90,120),pillar(r+72,y-90,120),beam(r,y-165,220),target(r,y-215),beam(x,y-285,520),target(x,y-335)]}}
];

const SPRITES={heroIdle:0,heroTension:1,heroFlying:2,heroStunned:3,bossIdle:4,bossSmug:5,bossPanic:6,bossDefeated:7};
const officeBirdAtlas=new Image();
officeBirdAtlas.src='./assets/sprites/office-birds-vectors.svg';
window.officeBirdAtlas=officeBirdAtlas;
let progress=loadProgress(),levelIndex=0,ball,sling,mouseConstraint,anchor,shotsUsed=0,released=false,detached=false,respawnQueued=false,targets=[],levelFinished=false,floorY=0,levelStartTime=0,score=0,lowSpeedFrames=0,shotStartedAt=0,paused=false;
let particles=[],impactRings=[],flash=0,heroStunnedUntil=0;
const woodDamageLedger=new Map();

function loadProgress(){try{const s=JSON.parse(localStorage.getItem(STORAGE_KEY));if(s?.levels?.length===LEVELS.length)return s}catch(_){}return{unlocked:1,levels:LEVELS.map(()=>({stars:0,bestScore:0}))}}
function saveProgress(){localStorage.setItem(STORAGE_KEY,JSON.stringify(progress))}
function remainingShots(){return Math.max(0,LEVELS[levelIndex].shots-shotsUsed)}
function aliveTargets(){return targets.filter(t=>!t.defeated).length}
function currentStars(){const r=remainingShots();return r>=2?3:r===1?2:1}
function setStatus(t){statusEl.textContent=t}
function renderShotRack(){shotRack.innerHTML='';for(let i=0;i<LEVELS[levelIndex].shots;i++){const d=document.createElement('span');d.className=`shot-dot${i<shotsUsed?' used':''}`;shotRack.appendChild(d)}}
function updateHud(){levelEl.textContent=`${levelIndex+1}/${LEVELS.length} — ${LEVELS[levelIndex].name}`;shotsEl.textContent=remainingShots();targetsEl.textContent=aliveTargets();speedEl.textContent=ball?Vector.magnitude(ball.velocity).toFixed(1):'0.0';scoreEl.textContent=score;starsEl.textContent='★'.repeat(progress.levels[levelIndex].stars)+'☆'.repeat(3-progress.levels[levelIndex].stars);renderShotRack()}

function woodRender(kind){return kind==='beam'?{fillStyle:'#c9823c',strokeStyle:'#6f3b18',lineWidth:3}:{fillStyle:'#a95d2b',strokeStyle:'#5a2f16',lineWidth:3}}
function setupWood(b,kind,w,h){b.gameType='structure';b.material='wood';b.woodKind=kind;b.woodWidth=w;b.woodHeight=h;b.maxHealth=kind==='beam'?105:125;b.health=b.maxHealth;b.damageState=0;b.breakable=true;b.isSupport=kind==='pillar';woodDamageLedger.set(b.id,{health:b.health,damageState:0});return b}
function makeBeam(x,y,w){return setupWood(Bodies.rectangle(x,y,w,30,{density:.0024,friction:.72,frictionStatic:.9,frictionAir:.008,restitution:.03,chamfer:{radius:7},render:woodRender('beam')}),'beam',w,30)}
function makePillar(x,y,h){return setupWood(Bodies.rectangle(x,y,34,h,{density:.0027,friction:.75,frictionStatic:.95,frictionAir:.008,restitution:.02,chamfer:{radius:5},render:woodRender('pillar')}),'pillar',34,h)}
function makeTarget(x,y){const t=Bodies.circle(x,y,27,{density:.0014,friction:.28,restitution:.08,render:{visible:false}});t.gameType='target';t.defeated=false;t.start={x,y};t.variant=targets.length%2;targets.push(t);return t}

function createProjectile(){ball=Bodies.circle(anchor.x,anchor.y,34,{density:.004,restitution:.35,friction:.12,frictionAir:.004,render:{visible:false}});ball.gameType='projectile';sling=Constraint.create({pointA:anchor,bodyB:ball,stiffness:.018,damping:.035,length:0,render:{visible:false}});World.add(engine.world,[ball,sling]);released=false;detached=false;respawnQueued=false;lowSpeedFrames=0;shotStartedAt=0;heroStunnedUntil=0;if(!levelFinished)setStatus('Потяни героя назад')}
function setupMouse(){const mouse=Mouse.create(canvas);mouse.pixelRatio=render.options.pixelRatio;mouseConstraint=MouseConstraint.create(engine,{mouse,constraint:{stiffness:.18,damping:.12,render:{visible:false}}});Events.on(mouseConstraint,'startdrag',e=>{if(paused||levelFinished||e.body!==ball||detached)return;released=false;setStatus('Натяжение')});Events.on(mouseConstraint,'enddrag',e=>{if(paused||levelFinished||e.body!==ball||detached)return;const stretch=Vector.magnitude(Vector.sub(ball.position,anchor));if(stretch<45){setStatus('Потяни сильнее');return}released=true;shotsUsed++;shotStartedAt=performance.now();setStatus('Запуск');updateHud()});World.add(engine.world,mouseConstraint);render.mouse=mouse}

function loadLevel(index){woodDamageLedger.clear();paused=false;engine.timing.timeScale=1;pausePanel.classList.remove('show');pauseBtn.textContent='Пауза';levelIndex=Math.max(0,Math.min(index,LEVELS.length-1));Composite.clear(engine.world,false);targets=[];particles=[];impactRings=[];shotsUsed=0;score=0;levelFinished=false;result.classList.remove('show');levelMenu.classList.remove('show');floorY=innerHeight-110;anchor={x:Math.max(320,innerWidth*.21),y:floorY-210};const towerX=Math.max(innerWidth*.72,anchor.x+650);World.add(engine.world,Bodies.rectangle(innerWidth/2,floorY+45,innerWidth+500,90,{isStatic:true,friction:1,render:{fillStyle:'#283846',strokeStyle:'#17232d',lineWidth:2}}));createProjectile();World.add(engine.world,LEVELS[levelIndex].build({x:towerX,y:floorY,beam:makeBeam,pillar:makePillar,target:makeTarget}));setupMouse();levelStartTime=performance.now();updateHud()}
function queueProjectile(){if(respawnQueued||levelFinished)return;syncWoodDamage();respawnQueued=true;setTimeout(()=>{if(levelFinished)return;if(ball)World.remove(engine.world,ball);if(sling)World.remove(engine.world,sling);remainingShots()>0?createProjectile():finishLevel(false)},350)}
function defeatTarget(t){if(!t||t.defeated)return;t.defeated=true;t.defeatedAt=performance.now();score+=100;burst(t.position.x,t.position.y,16,'#f7c56d');updateHud();if(aliveTargets()===0)finishLevel(true)}
function finishLevel(won){if(levelFinished)return;levelFinished=true;if(won){const stars=currentStars(),timeBonus=Math.max(0,Math.round(300-(performance.now()-levelStartTime)/100)),finalScore=score+remainingShots()*250+timeBonus;score=finalScore;const rec=progress.levels[levelIndex];rec.stars=Math.max(rec.stars,stars);rec.bestScore=Math.max(rec.bestScore,finalScore);progress.unlocked=Math.max(progress.unlocked,Math.min(LEVELS.length,levelIndex+2));saveProgress();resultTitle.textContent='Уровень пройден!';resultStars.textContent='★'.repeat(stars)+'☆'.repeat(3-stars);resultText.textContent=`Счёт: ${finalScore}. Осталось запусков: ${remainingShots()}.`;nextBtn.hidden=false;nextBtn.textContent=levelIndex===LEVELS.length-1?'К уровням':'Следующий уровень';setStatus('Уровень пройден')}else{resultTitle.textContent='Попробуй ещё раз';resultStars.textContent='☆☆☆';resultText.textContent=`Осталось менеджеров: ${aliveTargets()}.`;nextBtn.hidden=true;setStatus('Запуски закончились')}updateHud();result.classList.add('show')}

function renderLevelMenu(){const total=progress.levels.reduce((s,l)=>s+l.stars,0);totalStarsEl.textContent=`${total}/${LEVELS.length*3}`;levelGrid.innerHTML='';LEVELS.forEach((l,i)=>{const unlocked=i<progress.unlocked,rec=progress.levels[i],btn=document.createElement('button');btn.className='level-tile';btn.disabled=!unlocked;btn.innerHTML=`<span class="level-number">${i+1}</span><strong>${l.name}</strong><span class="level-stars">${unlocked?'★'.repeat(rec.stars)+'☆'.repeat(3-rec.stars):'🔒'}</span><small>${rec.bestScore?`Рекорд: ${rec.bestScore}`:'Не пройден'}</small>`;btn.onclick=()=>loadLevel(i);levelGrid.appendChild(btn)})}
function showMenu(){paused=true;engine.timing.timeScale=0;pausePanel.classList.remove('show');renderLevelMenu();levelMenu.classList.add('show');result.classList.remove('show')}
function togglePause(force){if(levelFinished||levelMenu.classList.contains('show'))return;paused=typeof force==='boolean'?force:!paused;engine.timing.timeScale=paused?0:1;pausePanel.classList.toggle('show',paused);pauseBtn.textContent=paused?'Продолжить':'Пауза'}

function burst(x,y,count,color){for(let i=0;i<count;i++){const a=Math.random()*Math.PI*2,s=1.5+Math.random()*4;particles.push({x,y,vx:Math.cos(a)*s,vy:Math.sin(a)*s-1,life:28+Math.random()*22,size:2+Math.random()*5,color})}}
function impact(x,y,power){impactRings.push({x,y,r:8,life:18,power});flash=Math.max(flash,Math.min(.18,power/90));burst(x,y,Math.min(22,6+Math.round(power)),'#d9a15f')}
function updateEffects(){for(const p of particles){p.x+=p.vx;p.y+=p.vy;p.vy+=.15;p.vx*=.98;p.life--}particles=particles.filter(p=>p.life>0);for(const r of impactRings){r.r+=3+r.power*.08;r.life--}impactRings=impactRings.filter(r=>r.life>0);flash*=.82}
function updateWoodLook(body){const ratio=Math.max(0,body.health/body.maxHealth);const next=ratio>.66?0:ratio>.32?1:2;body.damageState=next;if(next===0){body.render.fillStyle=body.woodKind==='beam'?'#c9823c':'#a95d2b';body.render.strokeStyle=body.woodKind==='beam'?'#6f3b18':'#5a2f16';body.render.lineWidth=3}else if(next===1){body.render.fillStyle=body.woodKind==='beam'?'#b96f31':'#965025';body.render.strokeStyle='#54270f';body.render.lineWidth=3}else{body.render.fillStyle=body.woodKind==='beam'?'#8e4e25':'#713918';body.render.strokeStyle='#321507';body.render.lineWidth=4}woodDamageLedger.set(body.id,{health:body.health,damageState:body.damageState})}
function syncWoodDamage(){for(const b of Composite.allBodies(engine.world)){if(b.material!=='wood'||b.broken)continue;const saved=woodDamageLedger.get(b.id);if(saved){b.health=saved.health;b.damageState=saved.damageState}updateWoodLook(b)}}
function makeWoodFragment(source,x,y,w,h){const piece=Bodies.rectangle(x,y,w,h,{density:.0021,friction:.72,frictionStatic:.9,frictionAir:.012,restitution:.08,chamfer:{radius:4},render:{fillStyle:source.render.fillStyle,strokeStyle:'#3b1b0c',lineWidth:3}});piece.gameType='debris';piece.material='wood';piece.createdAt=performance.now();Body.setAngle(piece,source.angle);Body.setVelocity(piece,{x:source.velocity.x+(Math.random()-.5)*2.5,y:source.velocity.y-1-Math.random()*1.5});Body.setAngularVelocity(piece,source.angularVelocity+(Math.random()-.5)*.18);return piece}
function breakWood(body,contact){if(!body||body.broken||!body.breakable)return;body.broken=true;const horizontal=body.woodKind==='beam',gap=5,partW=horizontal?(body.woodWidth-gap)/2:body.woodWidth,partH=horizontal?body.woodHeight:(body.woodHeight-gap)/2;const local=horizontal?{x:body.woodWidth*.26,y:0}:{x:0,y:body.woodHeight*.26};const c=Math.cos(body.angle),si=Math.sin(body.angle),offset={x:local.x*c-local.y*si,y:local.x*si+local.y*c};const a=makeWoodFragment(body,body.position.x-offset.x,body.position.y-offset.y,partW,partH),b=makeWoodFragment(body,body.position.x+offset.x,body.position.y+offset.y,partW,partH);World.remove(engine.world,body);World.add(engine.world,[a,b]);burst(contact?.x||body.position.x,contact?.y||body.position.y,18,'#c78342');impactRings.push({x:contact?.x||body.position.x,y:contact?.y||body.position.y,r:8,life:22,power:8});score+=body.isSupport?250:100;setStatus(body.isSupport?'Несущая опора сломана':'Дерево раскололось');updateHud()}
function damageWood(body,power,contact){if(!body||body.material!=='wood'||!body.breakable||body.broken)return;const saved=woodDamageLedger.get(body.id);if(saved)body.health=saved.health;const damage=Math.max(0,(power-2.2)*10.5);if(damage<4)return;body.health=Math.max(0,body.health-damage);updateWoodLook(body);burst(contact?.x||body.position.x,contact?.y||body.position.y,Math.min(10,3+Math.round(damage/9)),'#d6a065');if(body.health<=0||power>11.5)breakWood(body,contact)}
function drawWoodDamage(ctx){for(const b of Composite.allBodies(engine.world)){if(b.material!=='wood'||!b.damageState||b.broken)continue;ctx.save();ctx.translate(b.position.x,b.position.y);ctx.rotate(b.angle);ctx.strokeStyle=b.damageState===1?'rgba(55,26,10,.75)':'rgba(35,12,4,.95)';ctx.lineWidth=b.damageState===1?2:3;const w=b.woodWidth,h=b.woodHeight;ctx.beginPath();if(b.woodKind==='beam'){ctx.moveTo(-w*.18,-h*.45);ctx.lineTo(-w*.08,0);ctx.lineTo(-w*.15,h*.45);if(b.damageState>1){ctx.moveTo(w*.12,-h*.45);ctx.lineTo(w*.03,-2);ctx.lineTo(w*.18,h*.45)}}else{ctx.moveTo(-w*.45,-h*.18);ctx.lineTo(0,-h*.06);ctx.lineTo(w*.45,-h*.14);if(b.damageState>1){ctx.moveTo(-w*.45,h*.12);ctx.lineTo(2,h*.03);ctx.lineTo(w*.45,h*.18)}}ctx.stroke();ctx.restore()}}

function atlasReady(){const a=window.officeBirdAtlas;return a&&a.complete&&a.naturalWidth>0}
function drawSprite(ctx,index,x,y,w,h,angle=0){if(!atlasReady())return false;const a=window.officeBirdAtlas,cols=4,rows=2,sw=a.naturalWidth/cols,sh=a.naturalHeight/rows,sx=(index%cols)*sw,sy=Math.floor(index/cols)*sh;ctx.save();ctx.translate(x,y);ctx.rotate(angle);ctx.shadowColor='rgba(0,0,0,.28)';ctx.shadowBlur=10;ctx.shadowOffsetY=6;ctx.drawImage(a,sx,sy,sw,sh,-w/2,-h/2,w,h);ctx.restore();return true}
function drawFallbackHero(ctx){const{x,y}=ball.position;ctx.save();ctx.translate(x,y);ctx.rotate(ball.angle);ctx.fillStyle='#26364a';ctx.beginPath();ctx.arc(0,0,32,0,Math.PI*2);ctx.fill();ctx.fillStyle='#f1c7a4';ctx.beginPath();ctx.arc(4,-8,13,0,Math.PI*2);ctx.fill();ctx.restore()}
function drawFallbackBoss(ctx,t){ctx.save();ctx.translate(t.position.x,t.position.y);ctx.rotate(t.angle);ctx.fillStyle=t.defeated?'#727b86':'#2b3543';ctx.fillRect(-20,-20,40,55);ctx.fillStyle='#e9bf9d';ctx.beginPath();ctx.arc(0,-25,16,0,Math.PI*2);ctx.fill();ctx.restore()}

function drawBackground(ctx){const w=render.canvas.width,h=render.canvas.height,pr=render.options.pixelRatio||1;ctx.save();ctx.setTransform(1,0,0,1,0,0);const g=ctx.createLinearGradient(0,0,0,h);g.addColorStop(0,'#5ba9df');g.addColorStop(.55,'#bce7fb');g.addColorStop(1,'#d8e4e7');ctx.fillStyle=g;ctx.fillRect(0,0,w,h);ctx.globalAlpha=.22;for(let i=0;i<13;i++){const bw=90*pr+(i%3)*22*pr,bh=(180+(i%5)*50)*pr,x=i*(w/11)-50*pr,y=h-floorY*pr-bh+70*pr;ctx.fillStyle=i%2?'#37698b':'#4a7897';ctx.fillRect(x,y,bw,bh);ctx.fillStyle='rgba(255,227,146,.48)';for(let wx=x+14*pr;wx<x+bw-10*pr;wx+=26*pr)for(let wy=y+18*pr;wy<y+bh-15*pr;wy+=30*pr)ctx.fillRect(wx,wy,10*pr,12*pr)}ctx.globalAlpha=1;ctx.fillStyle='rgba(255,255,255,.38)';ctx.fillRect(0,(floorY-10)*pr,w,12*pr);ctx.restore()}
function drawSlingshot(ctx){ctx.save();ctx.lineCap='round';ctx.lineJoin='round';ctx.shadowColor='rgba(0,0,0,.28)';ctx.shadowBlur=12;ctx.shadowOffsetY=7;ctx.strokeStyle='#6f3518';ctx.lineWidth=24;ctx.beginPath();ctx.moveTo(anchor.x,floorY-2);ctx.lineTo(anchor.x,anchor.y+16);ctx.moveTo(anchor.x,anchor.y+24);ctx.lineTo(anchor.x-48,anchor.y-45);ctx.moveTo(anchor.x,anchor.y+24);ctx.lineTo(anchor.x+48,anchor.y-45);ctx.stroke();ctx.shadowColor='transparent';ctx.strokeStyle='#c37a35';ctx.lineWidth=8;ctx.beginPath();ctx.moveTo(anchor.x-3,floorY-8);ctx.lineTo(anchor.x-3,anchor.y+16);ctx.stroke();ctx.fillStyle='#4e2c18';ctx.beginPath();ctx.ellipse(anchor.x,floorY+2,58,12,0,0,Math.PI*2);ctx.fill();if(!detached&&ball){ctx.strokeStyle='#2d1a12';ctx.lineWidth=7;ctx.beginPath();ctx.moveTo(anchor.x-48,anchor.y-45);ctx.lineTo(ball.position.x,ball.position.y);ctx.lineTo(anchor.x+48,anchor.y-45);ctx.stroke()}ctx.restore()}
function drawHero(ctx){if(!ball)return;let sprite=SPRITES.heroIdle,w=116,h=116,angle=ball.angle;if(mouseConstraint?.body===ball&&!detached){const stretch=Vector.magnitude(Vector.sub(ball.position,anchor));if(stretch>30){sprite=SPRITES.heroTension;w=150;h=125;angle=0}}else if(detached){sprite=performance.now()<heroStunnedUntil?SPRITES.heroStunned:SPRITES.heroFlying;w=sprite===SPRITES.heroStunned?125:130;h=sprite===SPRITES.heroStunned?110:118}if(!drawSprite(ctx,sprite,ball.position.x,ball.position.y,w,h,angle))drawFallbackHero(ctx)}
function drawTargets(ctx){for(const t of targets){const moved=Vector.magnitude(Vector.sub(t.position,t.start));let sprite=t.variant?SPRITES.bossSmug:SPRITES.bossIdle;if(t.defeated)sprite=SPRITES.bossDefeated;else if(moved>20||Math.abs(t.angle)>.22)sprite=SPRITES.bossPanic;const w=t.defeated?112:100,h=t.defeated?90:112;if(!drawSprite(ctx,sprite,t.position.x,t.position.y,w,h,t.angle))drawFallbackBoss(ctx,t)}}
function drawTrajectory(ctx){if(!mouseConstraint?.body||mouseConstraint.body!==ball||detached||paused)return;const pull=Vector.sub(anchor,ball.position),distance=Vector.magnitude(pull);if(distance<25)return;let p={...ball.position},v=Vector.mult(Vector.normalise(pull),Math.min(distance,320)*.125);const g=.278;ctx.save();for(let i=0;i<34;i++){p.x+=v.x;p.y+=v.y;v.y+=g;if(i%2)continue;ctx.beginPath();ctx.fillStyle=`rgba(255,230,132,${.92-i/45})`;ctx.arc(p.x,p.y,4.5,0,Math.PI*2);ctx.fill()}ctx.restore()}
function drawEffects(ctx){ctx.save();for(const r of impactRings){ctx.globalAlpha=r.life/18;ctx.strokeStyle='#ffe08a';ctx.lineWidth=3;ctx.beginPath();ctx.arc(r.x,r.y,r.r,0,Math.PI*2);ctx.stroke()}for(const p of particles){ctx.globalAlpha=Math.min(1,p.life/18);ctx.fillStyle=p.color;ctx.beginPath();ctx.arc(p.x,p.y,p.size,0,Math.PI*2);ctx.fill()}ctx.restore();if(flash>0){ctx.save();ctx.setTransform(1,0,0,1,0,0);ctx.fillStyle=`rgba(255,239,178,${flash})`;ctx.fillRect(0,0,render.canvas.width,render.canvas.height);ctx.restore()}}

Events.on(engine,'collisionStart',event=>{for(const pair of event.pairs){if(pair.bodyA!==ball&&pair.bodyB!==ball)continue;const other=pair.bodyA===ball?pair.bodyB:pair.bodyA,rv=Vector.sub(pair.bodyA.velocity,pair.bodyB.velocity),normal=pair.collision?.normal||{x:1,y:0},power=Math.abs(Vector.dot(rv,normal));if(power>2.2){const c=pair.collision?.supports?.[0]||other.position;impact(c.x,c.y,power);heroStunnedUntil=performance.now()+Math.min(900,250+power*45)}if(other.gameType==='target'&&power>2.2){defeatTarget(other);setStatus('Менеджер выбит')}else if(other.gameType==='structure'&&power>2.5){const c=pair.collision?.supports?.[0]||other.position;damageWood(other,power,c);score+=Math.min(25,Math.round(power));if(!other.broken)setStatus(other.damageState?'Дерево повреждено':'Сильный удар');updateHud()}}});
Events.on(engine,'beforeUpdate',()=>{syncWoodDamage();if(!ball)return;if(released&&!detached&&sling){const offset=Vector.sub(ball.position,anchor),distance=Vector.magnitude(offset),toward=Vector.dot(ball.velocity,Vector.normalise(Vector.mult(offset,-1)));if(distance<48&&toward>1.2){World.remove(engine.world,sling);sling=null;detached=true;released=false;setStatus('Полёт')}}for(const t of targets){if(t.defeated)continue;const moved=Vector.magnitude(Vector.sub(t.position,t.start));if(t.position.y>floorY-36||moved>115||Math.abs(t.angle)>1.1)defeatTarget(t)}if(detached&&!respawnQueued){const speed=Vector.magnitude(ball.velocity);lowSpeedFrames=speed<.75?lowSpeedFrames+1:0;const outside=ball.position.x>innerWidth+220||ball.position.x<-220||ball.position.y>innerHeight+260,timeout=shotStartedAt&&performance.now()-shotStartedAt>6500;if(outside||lowSpeedFrames>24||timeout)queueProjectile()}updateEffects();updateHud()});
Events.on(render,'beforeRender',()=>drawBackground(render.context));
Events.on(render,'afterRender',()=>{if(!anchor)return;const ctx=render.context;drawTrajectory(ctx);drawSlingshot(ctx);drawWoodDamage(ctx);drawTargets(ctx);drawHero(ctx);drawEffects(ctx)});

resetBtn.onclick=()=>loadLevel(levelIndex);debugBtn.onclick=()=>{render.options.wireframes=!render.options.wireframes;debugBtn.textContent=render.options.wireframes?'Debug ON':'Debug'};menuBtn.onclick=showMenu;pauseBtn.onclick=()=>togglePause();resumeBtn.onclick=()=>togglePause(false);pauseRestartBtn.onclick=()=>loadLevel(levelIndex);pauseMenuBtn.onclick=showMenu;retryBtn.onclick=()=>loadLevel(levelIndex);nextBtn.onclick=()=>levelIndex===LEVELS.length-1?showMenu():loadLevel(levelIndex+1);$('closeMenuBtn').onclick=()=>{levelMenu.classList.remove('show');paused=false;engine.timing.timeScale=1};
window.addEventListener('keydown',e=>{if(e.key.toLowerCase()==='r')loadLevel(levelIndex);if(e.key==='Escape')togglePause();if(e.code==='Space'){e.preventDefault();togglePause()}});window.addEventListener('resize',()=>loadLevel(levelIndex));
Render.run(render);Runner.run(runner,engine);loadLevel(0);renderLevelMenu();showMenu();
